[project]
name = "big0-dev-github-io"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "jinja2>=3.1.6",
    "markdown>=3.7",
    "minify-html>=0.16.4",
    "pyyaml>=6.0.2",
    "rcssmin>=1.2.1",
]
